image: Visual Studio 2019

shallow_clone: false

before_build:
  - appveyor-retry dotnet restore -v Minimal

build_script:
  - dotnet build Rebus.SignalR -c Release 
  - dotnet build Rebus.SignalR.Tests -c Release 
  - dotnet build Rebus.SignalR.Samples -c Release 

test: off

test_script:
- cmd: cd Rebus.SignalR.Tests
- cmd: nuget install Appveyor.TestLogger -Version 2.0.0
- cmd: cd ..
- cmd: dotnet test Rebus.SignalR.Tests/Rebus.SignalR.Tests.csproj -c Release --test-adapter-path:. --logger:Appveyor --no-build